AR_LOOP_MODE = {
    NO_LOOP = 0,
    LOOP = 1,
    PING_PONG = 2,
    NO_LOOP_SMOOTH = 3,
}

AR_PLAYBACK_DIRECTION = {
    FORWARD = 1,
    REVERSE = -1,
}

AR_PLAYBACK_TYPE = {
    ABSOLUTE = "absolute",
    RELATIVE = "relative",
}

AR_ANIMATION_STATUS = {
    NOT_STARTED = 0,
    PLAYING = 1,
    FINISHED = 2,
    SMOOTH_RETURN = 3
}
AR_FRAME_INTERVAL = 0.02

AR_ACTIVATION_MODE = {
    PLAY_RESET = 0,
    PLAY_STOP = 1,
    FORWARDS_BACKWARDS = 2,
    FORWARDS_BACKWARDS_STOP = 3,
    TELEPORT = 4, -- New mode
}